name: Build, Run and Test

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build the Docker image
        run: docker build -t my-app .

      - name: Run the Docker container
        run: docker run -d -p 5000:5000 --name my-running-app my-app

      - name: Test the application
        run: |
          sleep 3
          curl http://localhost:5000

      - name: Stop and cleanup container
        if: always()
        run: |
          docker stop my-running-app || true
          docker rm my-running-app || true

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-build-artifact
          path: .
