# anything.yaml
name: build-and-run

on:
  push:
  workflow_dispatch:

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
        - name: checkout code
          uses: actions/checkout@v4

        - name: build the docker image
          run: docker build -t my-app .

        - name: run the docker container
          run: docker run -d -p 5000:5000 --name my-app my-app

        - name: test the application
          run: |
            sleep 3
            curl http://localhost:5000

        - name: cleanup container
          if: always()
          run: |
            docker stop my-app || true
            docker rm my-app || true
